-- =============================================================
-- Migration: Triage, Stamps, and Charm Tags
-- =============================================================

-- 1. Stamps table: emotion stamp records
CREATE TABLE stamps (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  novel_id bigint REFERENCES novels(id) ON DELETE CASCADE NOT NULL,
  emoji text NOT NULL,
  episode_number int,
  created_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX idx_stamps_user_novel ON stamps(user_id, novel_id);
CREATE INDEX idx_stamps_created_at ON stamps(created_at DESC);

-- 2. Charm tags master table (system + user-defined)
CREATE TABLE charm_tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  is_system boolean DEFAULT false NOT NULL,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now() NOT NULL,
  UNIQUE(name, user_id)
);

CREATE INDEX idx_charm_tags_user ON charm_tags(user_id);

-- 3. Many-to-many: stamps <-> charm_tags
CREATE TABLE stamp_charm_tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stamp_id bigint REFERENCES stamps(id) ON DELETE CASCADE NOT NULL,
  charm_tag_id bigint REFERENCES charm_tags(id) ON DELETE CASCADE NOT NULL,
  UNIQUE(stamp_id, charm_tag_id)
);

-- 4. Triage sessions table (Zeigarnik effect: save incomplete sessions)
CREATE TABLE triage_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  total_cards int NOT NULL DEFAULT 0,
  sorted_cards int NOT NULL DEFAULT 0,
  is_complete boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT now() NOT NULL,
  completed_at timestamptz
);

CREATE INDEX idx_triage_sessions_user ON triage_sessions(user_id, is_complete);

-- 5. Triage results table: per-card sort result
CREATE TABLE triage_results (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id bigint REFERENCES triage_sessions(id) ON DELETE CASCADE NOT NULL,
  bookmark_id bigint REFERENCES bookmarks(id) ON DELETE CASCADE NOT NULL,
  tier smallint NOT NULL CHECK (tier >= 0 AND tier <= 3),
  sorted_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX idx_triage_results_session ON triage_results(session_id);

-- 6. Add new columns to bookmarks
ALTER TABLE bookmarks
  ADD COLUMN IF NOT EXISTS tier smallint DEFAULT -1,
  ADD COLUMN IF NOT EXISTS heat_score real DEFAULT 0.0,
  ADD COLUMN IF NOT EXISTS last_stamped_at timestamptz;

-- =============================================================
-- RLS Policies
-- =============================================================

ALTER TABLE stamps ENABLE ROW LEVEL SECURITY;
ALTER TABLE charm_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE stamp_charm_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE triage_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE triage_results ENABLE ROW LEVEL SECURITY;

-- Stamps: users can CRUD their own
CREATE POLICY "Users can view own stamps" ON stamps FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own stamps" ON stamps FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own stamps" ON stamps FOR DELETE USING (auth.uid() = user_id);

-- Charm tags: users can see system tags + own tags
CREATE POLICY "Users can view system and own tags" ON charm_tags FOR SELECT
  USING (is_system = true OR auth.uid() = user_id);
CREATE POLICY "Users can insert own tags" ON charm_tags FOR INSERT
  WITH CHECK (auth.uid() = user_id AND is_system = false);
CREATE POLICY "Users can delete own tags" ON charm_tags FOR DELETE
  USING (auth.uid() = user_id AND is_system = false);

-- Stamp charm tags: users can manage their own stamp's tags
CREATE POLICY "Users can view own stamp tags" ON stamp_charm_tags FOR SELECT
  USING (EXISTS (SELECT 1 FROM stamps WHERE stamps.id = stamp_id AND stamps.user_id = auth.uid()));
CREATE POLICY "Users can insert own stamp tags" ON stamp_charm_tags FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM stamps WHERE stamps.id = stamp_id AND stamps.user_id = auth.uid()));
CREATE POLICY "Users can delete own stamp tags" ON stamp_charm_tags FOR DELETE
  USING (EXISTS (SELECT 1 FROM stamps WHERE stamps.id = stamp_id AND stamps.user_id = auth.uid()));

-- Triage sessions: users can CRUD their own
CREATE POLICY "Users can view own triage sessions" ON triage_sessions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own triage sessions" ON triage_sessions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own triage sessions" ON triage_sessions FOR UPDATE USING (auth.uid() = user_id);

-- Triage results: users can manage via their own sessions
CREATE POLICY "Users can view own triage results" ON triage_results FOR SELECT
  USING (EXISTS (SELECT 1 FROM triage_sessions WHERE triage_sessions.id = session_id AND triage_sessions.user_id = auth.uid()));
CREATE POLICY "Users can insert own triage results" ON triage_results FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM triage_sessions WHERE triage_sessions.id = session_id AND triage_sessions.user_id = auth.uid()));

-- =============================================================
-- System charm tags seed data
-- =============================================================

INSERT INTO charm_tags (name, is_system, user_id) VALUES
  ('#伏線回収', true, NULL),
  ('#俺TUEEE', true, NULL),
  ('#感動', true, NULL),
  ('#ダークファンタジー', true, NULL),
  ('#ほのぼの', true, NULL),
  ('#頭脳戦', true, NULL),
  ('#恋愛', true, NULL),
  ('#成長物語', true, NULL),
  ('#世界観◎', true, NULL),
  ('#テンポ良い', true, NULL);
